# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: blang/latex:ubuntu
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: pdflatex Daniel-Wierdsma-Resume.tex
      - checkin